export const environment = {
    production: true,
    BSC_TESTNET_NODE: $ENV.BSC_TESTNET_NODE,
    GOERLI_TESTNET_NODE: $ENV.GOERLI_TESTNET_NODE,
    BESU_LOCAL_NODE: $ENV.BESU_LOCAL_NODE,
    BSC_BRIDGE_ADDRESS: $ENV.BSC_BRIDGE_ADDRESS,
    GOERLI_BRIDGE_ADDRESS: $ENV.GOERLI_BRIDGE_ADDRESS,
    BESU_BRIDGE_ADDRESS: $ENV.BESU_BRIDGE_ADDRESS,
    BSC_EVM_TOKEN_ADDRESS: $ENV.BSC_EVM_TOKEN_ADDRESS,
    GOERLI_EVM_TOKEN_ADDRESS: $ENV.GOERLI_EVM_TOKEN_ADDRESS,
    BESU_EVM_TOKEN_ADDRESS: $ENV.BESU_EVM_TOKEN_ADDRESS
};
